# Generated by Django 2.0.7 on 2018-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('global_rank', models.IntegerField(unique=True)),
                ('matches_won', models.IntegerField()),
                ('type_speed', models.IntegerField()),
                ('letters_typed', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Playing'), ('L', 'Lobby'), ('O', 'Offline')], max_length=10)),
                ('local_rank', models.IntegerField()),
            ],
        ),
    ]
