# Generated by Django 2.0.7 on 2018-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('LI', 'Log In'), ('L', 'Lobby'), ('P', 'Playing'), ('O', 'Offline')], max_length=10),
        ),
    ]
