# Generated by Django 2.0.7 on 2018-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='letters_typed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='local_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='type_speed',
            field=models.IntegerField(default=0),
        ),
    ]
