# Generated by Django 2.0.7 on 2018-07-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
